### ISSUE TITLE
Hackintosh question

### ISSUE THREAD

**Issue by michaeleisel** [leavez/Literal#1]
@leavez I was curious about your PC reported in https://github.com/ashfurrow/xcode-hardware-performance/pull/81

Would you say that the improvement to build speed is worth the sketchiness of hackintosh?

**Comment by leavez** [comment]
Yes, extremely recommended.

That’s my second Hackintosh. I have use another Hackintosh for more than 2 years. It saves me a lot of time. My daily working project spends about 5 mins for a fresh build on a normal MacBook. The code completion is also worked properly too, it helps a lot if you code swift.

I think iMac Pro is good too if don’t think it’s too expensive. 😂

**Comment by beefon** [comment]
Would you mind sharing your hardware component list please?
